rm ../policy/expert/MT50_Fixed/pick-place-v1.pth
rm ../policy/expert/MT50_Fixed/pick-place-wall-v1.pth
rm ../policy/expert/MT50_Fixed/peg-insert-side-v1.pth
rm ../policy/expert/MT50_Fixed/peg-unplug-side-v1.pth
rm ../policy/expert/MT50_Fixed/window-close-v1.pth
rm ../policy/expert/MT50_Fixed/dissassemble-v1.pth
rm ../policy/expert/MT50_Fixed/hammer-v1.pth
rm ../policy/expert/MT50_Fixed/plate-slide-back-side-v1.pth
rm ../policy/expert/MT50_Fixed/handle-press-side-v1.pth
rm ../policy/expert/MT50_Fixed/handle-pull-side-v1.pth
rm ../policy/expert/MT50_Fixed/stick-push-v1.pth
rm ../policy/expert/MT50_Fixed/stick-pull-v1.pth
rm ../policy/expert/MT50_Fixed/basketball-v1.pth
rm ../policy/expert/MT50_Fixed/faucet-open-v1.pth
rm ../policy/expert/MT50_Fixed/pick-out-of-hole-v1.pth
rm ../policy/expert/MT50_Fixed/assembly-v1.pth
rm ../policy/expert/MT50_Fixed/shelf-place-v1.pth
rm ../policy/expert/MT50_Fixed/push-back-v1.pth
rm ../policy/expert/MT50_Fixed/level-pull-v1.pth
rm ../policy/expert/MT50_Fixed/box-close-v1.pth

