cp ../../Multi-Task-RL/log/MT50_Single_Task/reach-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/reach-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/push-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/push-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/pick-place-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/pick-place-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/reach-wall-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/reach-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/pick-place-wall-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/pick-place-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/push-wall-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/push-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-open-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/door-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-close-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/door-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/drawer-open-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/drawer-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/drawer-close-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/drawer-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press_topdown-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/button-press_topdown-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/button-press-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press-topdown-wall-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/button-press-topdown-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press-wall-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/button-press-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/peg-insert-side-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/peg-insert-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/peg-unplug-side-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/peg-unplug-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/window-open-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/window-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/window-close-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/window-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/dissassemble-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/dissassemble-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/hammer-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/hammer-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/plate-slide-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-side-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/plate-slide-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-back-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/plate-slide-back-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-back-side-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/plate-slide-back-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-press-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/handle-press-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-pull-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/handle-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-press-side-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/handle-press-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-pull-side-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/handle-pull-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/stick-push-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/stick-push-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/stick-pull-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/stick-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/basket-ball-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/basket-ball-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/soccer-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/soccer-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/faucet-open-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/faucet-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/faucet-close-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/faucet-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/coffee-push-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/coffee-push-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/coffee-pull-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/coffee-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/coffee-button-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/coffee-button-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/sweep-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/sweep-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/sweep-into-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/sweep-into-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/pick-out-of-hole-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/pick-out-of-hole-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/assembly-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/assembly-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/shelf-place-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/shelf-place-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/push-back-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/push-back-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/lever-pull-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/lever-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/dial-turn-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/dial-turn-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/bin-picking-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/bin-picking-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/box-close-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/box-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/hand-insert-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/hand-insert-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-lock-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/door-lock-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-unlock-v1/Random/238/model/model_pf_best.pth ../policy/expert/MT50_Random/door-unlock-v1.pth
