cp ../../Multi-Task-RL/log/MT50_Single_Task/reach-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/reach-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/push-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/push-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/pick-place-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/pick-place-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/reach-wall-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/reach-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/pick-place-wall-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/pick-place-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/push-wall-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/push-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-open-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/door-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-close-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/door-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/drawer-open-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/drawer-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/drawer-close-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/drawer-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press_topdown-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/button-press-topdown-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/button-press-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press-topdown-wall-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/button-press-topdown-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/button-press-wall-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/button-press-wall-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/peg-insert-side-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/peg-insert-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/peg-unplug-side-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/peg-unplug-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/window-open-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/window-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/window-close-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/window-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/dissassemble-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/dissassemble-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/hammer-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/hammer-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/plate-slide-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-side-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/plate-slide-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-back-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/plate-slide-back-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/plate-slide-back-side-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/plate-slide-back-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-press-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/handle-press-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-pull-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/handle-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-press-side-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/handle-press-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/handle-pull-side-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/handle-pull-side-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/stick-push-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/stick-push-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/stick-pull-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/stick-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/basket-ball-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/basket-ball-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/soccer-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/soccer-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/faucet-open-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/faucet-open-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/faucet-close-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/faucet-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/coffee-push-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/coffee-push-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/coffee-pull-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/coffee-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/coffee-button-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/coffee-button-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/sweep-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/sweep-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/sweep-into-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/sweep-into-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/pick-out-of-hole-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/pick-out-of-hole-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/assembly-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/assembly-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/shelf-place-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/shelf-place-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/push-back-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/push-back-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/lever-pull-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/lever-pull-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/dial-turn-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/dial-turn-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/bin-picking-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/bin-picking-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/box-close-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/box-close-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/hand-insert-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/hand-insert-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-lock-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/door-lock-v1.pth
cp ../../Multi-Task-RL/log/MT50_Single_Task/door-unlock-v1/Fixed/238/model/model_pf_best.pth ../policy/expert/MT50_Fixed/door-unlock-v1.pth
